### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by AnubhabDebnathAgnikul** [AnubhabDebnathAgnikul/PubSub#2]
Make Test Benches for Unit Testing

**Comment by Shrivarshni-Ganesan** [comment]
"publish_init function with multiple threads for prototype_3"
clashes check is not working in the publish_init function
only the latest discovery message is written in the shared memory on the synchroniser side and not the messages from every threads

**Comment by Shrivarshni-Ganesan** [comment]
"checking the synchroniser response for different publisher accessing at the same time" in Pubsub_sample_3_test_branch_new_vishnu
1. only the first received discovery message is served (i.e) written in shared memory by the synchroniser and other publisher receives port clash message
2. shared memory is overwritten and not appended

**Comment by shrivarshnig** [comment]
"Checking the synchroniser function's internal server in prototype_3"
when publisher with different topic names but same port are given, then it is written in shm i.e. port check is missing for different topics

**Comment by shrivarshnig** [comment]
"Checking the synchroniser function for internal server in protoype_3"
when multiple processess are forked to send discovery message to the internal synchroniser server, the synchroniser throws "shm_open : Too many open files" and closes the port.

**Comment by AnubhabDebnathAgnikul** [comment]
Issue Resolved
Port Clash : Update Condition added
shm_open error: Shm_close for all file descriptors
